version: "3.9"
volumes:
  psysh-store:
services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
      target: ${APP_BUILD_TARGET}
    volumes:
      - type: bind
        source: ./src
        target: /data
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      - LOG_CHANNEL=${LOG_CHANNEL}
      - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    networks:
      - webdev

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - target: 80
        protocol: tcp
        mode: host
      - target: 443
        protocol: tcp
        mode: host
    environment:
      VIRTUAL_HOST: '${VIRTUAL_HOST}'
      SELF_SIGNED_HOST: '${SELF_SIGNED_HOST}'
    volumes:
      - type: bind
        source: ./src
        target: /data
    networks:
      - webdev

networks:
  webdev:
    external: true
    name: webdev
