version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1.7-node
        environment:
          DB_HOST: 127.0.0.1
          DB_CONNECTION: mysql
          DB_DATABASE: typing
          # DB_DATABASE: ${DB_DATABASE}

          DB_USERNAME: phper
          # DB_USERNAME: ${DB_USERNAME}
          
          DB_PASSWORD: 'secret'
          # DB_PASSWORD: '${DB_PASSWORD}'

      - image: cimg/mysql:8.0
        environment:
          DB_HOST: 127.0.0.1
          # MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_DATABASE: typing
          # MYSQL_USER: ${DB_USERNAME}
          MYSQL_USER: phper
          # MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_PASSWORD: 'secret'


    steps:
      - checkout
      - run: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: Update apt-get
          command: sudo apt-get update && sudo apt-get install -y npm nodejs mysql-client
      # - restore_cache:
      #     keys:
      #       - v1-npm-deps-{{ checksum "src/nuxt/package-lock.json" }}
      #       - v1-npm-deps-
            # working_directory:  ~/project/usr/local/lib/node_modules
      - run: 
          command: sudo npm install --location=global npm && npm i
          working_directory: ~/project/src/nuxt
      # - restore_cache:
      #     keys:
      #       - composer-v1-{{ checksum "src/laravel/composer.lock" }}
      #       - composer-v1-
      #     working_directory: ~/project/src/laravel
      - run: 
          command: composer install -n --prefer-dist
          working_directory: ~/project/src/laravel
      # - run: sudo docker-php-ext-install pdo_mysql

      - run: 
          command: php artisan migrate --force
          working_directory: ~/project/src/laravel
      - run: 
          command: php artisan test
          working_directory: ~/project/src/laravel
      - run: 
          command: npm test
          working_directory: ~/project/src/nuxt
      # - save_cache:
      #     key: composer-v1-{{ checksum "src/laravel/composer.lock" }}
      #     paths:
      #       - vendor
      #     # working_directory: ~/project/src/laravel
      # - save_cache:
      #     key: v1-npm-deps-{{ checksum "src/nuxt/package-lock.json" }}
      #     paths:
      #       - ~/project/usr/local/lib/node_modules

workflows:
  version: 2
  build:
    jobs:
      - build